name: Gitleaks
description: Run Gitleaks on Push and PR events
branding:
  color: purple
  icon: eye
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  result: "what it this"
    description: 'results of the scan'
